services:
  # Django Backend API
  - type: web
    name: motionmentor-api
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py migrate
    startCommand: gunicorn gemini_eyes.wsgi:application --chdir backend
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "motionmentor.onrender.com,localhost"
      - key: FRONTEND_URL
        value: https://motionmentor.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: motionmentor-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # Next.js Frontend
  - type: web
    name: motionmentor-app
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: "npm start -- --port $PORT"
    plan: standard
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: motionmentor-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false
    build:
      cache:
        - path: "frontend/node_modules"
        - path: "frontend/.next/cache"

databases:
  - name: motionmentor-db
    databaseName: motionmentor
    user: motionmentor_user
    plan: free 